exp: TextClassification 


mode:
  - train

  
models:
  hf_text_classification_model:
    -   /home/dreyes/Midterm/model1_base_eval/finetune1/models_1/iteration_1_model
      
trainfpath: /home/dreyes/Midterm/

validfpath:  /home/dreyes/Midterm/

modelfpath:  /home/dreyes/Midterm/model1_base_eval/finetune1/models_1/iteration_2_model

numLabels: 2


device: cuda: 0 

id2label:          
    0: NEUTRAL
    1: CONTRADICTION
    3: ENTAILMENT 


loadPretrained: True