
exp: TextClassification 


mode:
  - evaluate 

models:
  hf_text_classification_model:
    - ../NLP_426/MNLI_Model2/finetune2/iteration_1/model_1
      
datafpath: ../NLP_426/MNLI_Model2/Shared_BaseTrain_MNLI.tsv

predfpath: ../NLP_426/MNLI_Model2/finetune2/iteration_1/prediction_1/model2_iteration_1.tsv

device: cuda

seed: 315

giveAllLabels: True

